// app/api/export/[id]/route.ts
// BONUS: PDF export of the full audit report
import { NextRequest, NextResponse } from "next/server";
import { connectDB } from "@/lib/mongodb";
import { Audit } from "@/lib/models";
import type { AuditResult, AuditItem } from "@/types";

// We generate a clean HTML report and return it as a downloadable PDF-ready HTML file.
// For true PDF, integrate @react-pdf/renderer in a separate worker —
// this approach works without a Node.js worker thread limit on Vercel.

function generateReportHTML(audit: AuditResult): string {
  const date = new Date(audit.createdAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const rows = (audit.items ?? [])
    .map(
      (item: AuditItem) => `
      <tr>
        <td>${item.toolName}</td>
        <td>${item.currentPlan}</td>
        <td>$${item.currentSpend.toLocaleString()}/mo</td>
        <td class="${item.monthlySavings > 0 ? "savings" : "optimal"}">
          ${item.monthlySavings > 0 ? `-$${item.monthlySavings.toLocaleString()}/mo` : "✓ Optimal"}
        </td>
        <td>${item.reason}</td>
      </tr>`
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>AI Spend Audit Report — ${date}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #111; background: white; padding: 48px; }
    .header { border-bottom: 3px solid #16a34a; padding-bottom: 24px; margin-bottom: 32px; }
    .logo { font-size: 22px; font-weight: 800; color: #111; }
    .logo span { color: #16a34a; }
    .date { font-size: 13px; color: #6b7280; margin-top: 4px; }
    .hero { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 12px; padding: 28px; margin-bottom: 32px; text-align: center; }
    .hero-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.1em; color: #6b7280; margin-bottom: 8px; }
    .hero-amount { font-size: 56px; font-weight: 800; color: #16a34a; line-height: 1; }
    .hero-sub { font-size: 16px; color: #374151; margin-top: 8px; }
    .section-title { font-size: 16px; font-weight: 700; margin-bottom: 12px; color: #111; }
    .summary-box { background: #f9fafb; border-radius: 8px; padding: 20px; margin-bottom: 32px; font-size: 14px; line-height: 1.7; color: #374151; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 32px; font-size: 13px; }
    th { background: #f3f4f6; padding: 10px 12px; text-align: left; font-weight: 600; color: #374151; border-bottom: 2px solid #e5e7eb; }
    td { padding: 10px 12px; border-bottom: 1px solid #f3f4f6; vertical-align: top; }
    tr:last-child td { border-bottom: none; }
    .savings { color: #16a34a; font-weight: 700; }
    .optimal { color: #6b7280; }
    .footer { border-top: 1px solid #e5e7eb; padding-top: 20px; font-size: 12px; color: #9ca3af; display: flex; justify-content: space-between; }
    .credex-cta { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 20px; margin-bottom: 32px; }
    .credex-cta h3 { color: #16a34a; font-size: 15px; margin-bottom: 6px; }
    .credex-cta p { font-size: 13px; color: #374151; line-height: 1.6; }
    @media print { body { padding: 24px; } }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo"><span>AI</span>Audit by Credex</div>
    <div class="date">Report generated ${date}</div>
  </div>

  <div class="hero">
    <div class="hero-label">Total Potential Monthly Savings</div>
    <div class="hero-amount">$${(audit.totalMonthlySavings ?? 0).toLocaleString()}</div>
    <div class="hero-sub">
      $${(audit.totalAnnualSavings ?? 0).toLocaleString()}/year · 
      vs. $${(audit.totalCurrentSpend ?? 0).toLocaleString()}/mo current spend
    </div>
  </div>

  ${
    audit.aiSummary
      ? `<div class="section-title">Summary</div>
         <div class="summary-box">${audit.aiSummary}</div>`
      : ""
  }

  <div class="section-title">Tool-by-Tool Breakdown</div>
  <table>
    <thead>
      <tr>
        <th>Tool</th>
        <th>Current Plan</th>
        <th>Monthly Spend</th>
        <th>Savings</th>
        <th>Recommendation</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>

  ${
    (audit.totalMonthlySavings ?? 0) > 500
      ? `<div class="credex-cta">
          <h3>Capture these savings with Credex</h3>
          <p>Credex sources discounted AI credits for Cursor, Claude, ChatGPT and more from 
          companies that overforecast. For teams with &gt;$500/mo in savings, our advisors 
          typically find an additional 15–20% off retail pricing. Visit credex.rocks to book 
          a consultation.</p>
        </div>`
      : ""
  }

  <div class="footer">
    <span>Generated by AIAudit · credex.rocks</span>
    <span>Pricing verified from official vendor pages · See PRICING_DATA.md for sources</span>
  </div>

  <script>window.onload = () => window.print();</script>
</body>
</html>`;
}

export async function GET(
  _req: NextRequest,
  { params }: { params: { id: string } }
) {
  await connectDB();

  const audit = await Audit.findOne({ id: params.id }).lean() as AuditResult | null;
  if (!audit) {
    return NextResponse.json({ error: "Audit not found" }, { status: 404 });
  }

  // Strip PII from public export
  const safeAudit: AuditResult = { ...audit, email: undefined, companyName: undefined };

  const html = generateReportHTML(safeAudit);

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `inline; filename="ai-audit-${params.id.slice(0, 8)}.html"`,
    },
  });
}
